---
regions:
  - global

account-blocklist:
  - 123456789018

resource-types:
  targets:
    - IAMRole
    - IAMPolicy
    - IAMRolePolicy
    - IAMRolePolicyAttachment
    - IAMInstanceProfile

accounts:
  <Account ID>:
